---@meta

---@class CompParams

---@class BoatCompParams : CompParams
---@field gravity number
---@field max_speed number
---@field rotation_acceleration number
---@field rotation_deceleration number
---@field max_rotation_speed number
---@field max_ground_rotation_speed number
---@field turn_velocity_dependency number
---@field roll_speed number
---@field max_roll number
---@field roll_lift number
---@field bottom_y_shift number
---@field acceleration number
---@field water_splashes_number integer
---@field water_splashes_width number
---@field inventory_size integer
---@field layout_id string|nil
---@field player_pos_shift vec3

---@class SeatCompParams: CompParams
---@field player_pos_shift vec3
---@field player_pos_shift_after_unmount vec3

---@class LadderCompParams: CompParams
---@field	max_speed number
---@field	max_speed_cheat number
---@field	linear_damping number
---@field	linear_damping_cheat number
---@field	vdamping number
---@field	vdamping_cheat number
---@field	vert_acceleration number
---@field	vert_acceleration_cheat number
---@field	gravity_scale number

---@class Comp
---@field entity voxelcore.class.entity
---@field tsf voxelcore.class.entity.transform
---@field body voxelcore.class.entity.rigidbody
---@field rig voxelcore.class.entity.skeleton
---@field saved_data table
---@field args table
---@field p CompParams
---@field on_spawn fun(self: Comp)
---@field on_save fun(self: Comp)
---@field on_despawn fun(self: Comp)
---@field on_attacked fun(self: Comp, entity_id: integer, pid: integer)
---@field on_used fun(self: Comp, pid: integer)
---@field on_update fun(self: Comp, tps: number)
---@field on_physics_update fun(self: Comp, delta: number)
---@field on_render fun(self: Comp, delta: number)

---@class BoatComp : Comp
---@field p BoatCompParams
---@field player_unmount fun(self: BoatComp)
---@field player_mount fun(self: BoatComp, pid: integer)
---@field open_inventory fun(self: BoatComp)
---@field check_unmount fun(self: BoatComp)
---@field tp_player fun(self: BoatComp)
---@field move fun(self: BoatComp)
---@field spawn_move_water_splashes fun(self: BoatComp)
---@field spawn_fall_water_splashes fun(self: BoatComp)
---@field handle_water_behaviour fun(self: BoatComp)

---@class SeatComp : Comp
---@field p SeatCompParams
---@field player_unmount fun(self: SeatComp)
---@field player_mount fun(self: SeatComp, pid: integer)
---@field calc_rotated_shifted_pos fun(self: SeatComp, shift: vec3): vec3
---@field tp_player fun(self: SeatComp)
---@field check_unmount fun(self: SeatComp)
---@field check_destroyed fun(self: SeatComp)
---@field get_tag_name fun(self: SeatComp): string

---@class LadderComp : Comp
---@field p LadderCompParams
---@field player_stored table
---@field pbody voxelcore.class.entity.rigidbody
---@field player_unmount fun(self: LadderComp)
---@field player_mount fun(self: LadderComp )
---@field player_start_unmount fun(self: LadderComp )
---@field move fun(self: LadderComp , delta: number)
---@field sync_pos fun(self: LadderComp )
---@field check_unmount fun(self: LadderComp )
---@field save_player_body_settings fun(self: LadderComp )
---@field load_player_body_settings fun(self: LadderComp )
---@field get_tag_name fun(self: LadderComp): string
