---@meta

---@class comp_params

---@class boat_comp_params : comp_params
---@field gravity number
---@field max_speed number
---@field rotation_acceleration number
---@field rotation_deceleration number
---@field max_rotation_speed number
---@field max_ground_rotation_speed number
---@field turn_velocity_dependency number
---@field roll_speed number
---@field max_roll number
---@field roll_lift number
---@field bottom_y_shift number
---@field acceleration number
---@field water_splashes_number integer
---@field water_splashes_width number
---@field inventory_size integer
---@field layout_id string|nil
---@field player_pos_shift vec3

---@class seat_comp_params: comp_params
---@field enable_noclip boolean
---@field player_pos_shift vec3
---@field player_pos_shift_after_unmount vec3

---@class ladder_comp_params: comp_params
---@field	max_speed_xz number
---@field	max_speed_xz_cheat number
---@field	max_speed_y number
---@field	max_speed_y_cheat number
---@field	linear_damping number
---@field	linear_damping_cheat number
---@field	vdamping number
---@field	vdamping_cheat number
---@field	vert_acceleration number
---@field	vert_acceleration_cheat number
---@field	gravity number

---@class comp
---@field entity voxelcore.class.entity
---@field tsf voxelcore.class.entity.transform
---@field body voxelcore.class.entity.rigidbody
---@field rig voxelcore.class.entity.skeleton
---@field saved_data table
---@field args table
---@field p comp_params
---@field default_params comp_params
---@field on_spawn fun(self: comp)
---@field on_save fun(self: comp)
---@field on_despawn fun(self: comp)
---@field on_attacked fun(self: comp, entity_id: integer, pid: integer)
---@field on_used fun(self: comp, pid: integer)
---@field on_update fun(self: comp, tps: number)
---@field on_physics_update fun(self: comp, delta: number)
---@field on_render fun(self: comp, delta: number)

---@class boat_comp : comp
---@field p boat_comp_params
---@field player_unmount fun(self: boat_comp)
---@field player_mount fun(self: boat_comp, pid: integer)
---@field open_inventory fun(self: boat_comp)
---@field check_unmount fun(self: boat_comp)
---@field tp_player fun(self: boat_comp)
---@field move fun(self: boat_comp)
---@field spawn_move_water_splashes fun(self: boat_comp)
---@field spawn_fall_water_splashes fun(self: boat_comp)
---@field handle_water_behaviour fun(self: boat_comp)

---@class seat_comp : comp
---@field p seat_comp_params
---@field player_unmount fun(self: seat_comp)
---@field player_mount fun(self: seat_comp, pid: integer)
---@field calc_rotated_shifted_pos fun(self: seat_comp, shift: vec3): vec3
---@field tp_player fun(self: seat_comp)
---@field check_unmount fun(self: seat_comp)
---@field check_destroyed fun(self: seat_comp)
---@field get_tag_name fun(self: seat_comp): string

---@class ladder_comp : comp
---@field p ladder_comp_params
---@field player_stored table
---@field pbody voxelcore.class.entity.rigidbody
---@field player_unmount fun(self: ladder_comp)
---@field player_mount fun(self: ladder_comp )
---@field player_start_unmount fun(self: ladder_comp )
---@field move fun(self: ladder_comp , delta: number)
---@field sync_pos fun(self: ladder_comp )
---@field check_unmount fun(self: ladder_comp )
---@field save_player_body_settings fun(self: ladder_comp )
---@field load_player_body_settings fun(self: ladder_comp )
---@field get_tag_name fun(self: ladder_comp): string
---@field init_step_sounds fun(self: ladder_comp)
---@field play_step_sounds fun(self: ladder_comp)
